# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prattl < Formula
  desc "CLI tool for transcribing audio to text."
  homepage "https://prattl.co/"
  version "0.2.2"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    url "https://github.com/prattlOrg/prattl/releases/download/v0.2.2/prattl_darwin_all.tar.gz"
    sha256 "fbc5cd1de437dc69e974a3b0c8b11313a8df73291bd620000b2e609000b7bf5e"

    def install
      bin.install "prattl"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prattlOrg/prattl/releases/download/v0.2.2/prattl_linux_x86_64.tar.gz"
        sha256 "6da49f98368183c1b99821e3c36ac242e11aa6b0fad6721ef3f48bb202dfb06e"

        def install
          bin.install "prattl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prattlOrg/prattl/releases/download/v0.2.2/prattl_linux_arm64.tar.gz"
        sha256 "247becc8619238c1ef0fa21044488478f9ee606eed51fcf49cf5c0905d2b0703"

        def install
          bin.install "prattl"
        end
      end
    end
  end
end
