# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prattl < Formula
  desc "CLI tool for transcribing audio to text."
  homepage "https://prattl.co/"
  version "0.3.0"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    url "https://github.com/prattlOrg/prattl/releases/download/v0.3.0/prattl_darwin_all.tar.gz"
    sha256 "e4a3bbc54eab73003446dc245961c6eaf59381c489cea0d6e81da07ff30c124d"

    def install
      bin.install "prattl"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prattlOrg/prattl/releases/download/v0.3.0/prattl_linux_x86_64.tar.gz"
        sha256 "0ce6bdeaa8305557cefa1336164affce54905255033600fe9febe50d5d776ddf"

        def install
          bin.install "prattl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prattlOrg/prattl/releases/download/v0.3.0/prattl_linux_arm64.tar.gz"
        sha256 "a988b43a4c334069057218ef92c80a3238fa99149de2f9f6ced4dbe7d7189c4f"

        def install
          bin.install "prattl"
        end
      end
    end
  end
end
