# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prattl < Formula
  desc "CLI tool for transcribing audio to text."
  homepage "https://prattl.co/"
  version "0.4.1"
  license "MIT"

  depends_on "ffmpeg"

  on_macos do
    url "https://github.com/prattlOrg/prattl/releases/download/v0.4.1/prattl_darwin_all.tar.gz"
    sha256 "d9e05997810472b9c24c0963d6a4af6228cbc6ef0ad75a0fe02bfa50a5857d6a"

    def install
      bin.install "prattl"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prattlOrg/prattl/releases/download/v0.4.1/prattl_linux_x86_64.tar.gz"
        sha256 "b75a757d2214e845e41985a3ddb2df665bdf0575c3b996eb2866e8e8f23bc6c0"

        def install
          bin.install "prattl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prattlOrg/prattl/releases/download/v0.4.1/prattl_linux_arm64.tar.gz"
        sha256 "0b1ad71979187d9a586b60fedbd09281d76071e0d2db85c36cf7c64b1e725777"

        def install
          bin.install "prattl"
        end
      end
    end
  end
end
